global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ["gateway-service:8080"]
        labels:
          application: api-gateway

  - job_name: product-service
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ["product-service:8081"]
        labels:
          application: product-service


